### ISSUE TITLE
SyntaxError: Non-ASCII character '\xe2' in file ./whatismyschema.py on line 499, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

### ISSUE THREAD

**Issue by drstmane** [t1mm3/whatismyschema#1]
$ ./whatismyschema.py --help
  File "./whatismyschema.py", line 499
SyntaxError: Non-ASCII character '\xe2' in file ./whatismyschema.py on line 499, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by t1mm3** [comment]
I think this should be fixed by now
