### ISSUE TITLE
wrong TINYINT range (for standard SQL signed integer types)

### ISSUE THREAD

**Issue by drstmane** [t1mm3/whatismyschema#8]
$ cat /tmp/z.csv 
  0|  0|  0|  0|-127|-128|-129|-128|-129
127|128|255|256| 127| 127| 127| 128| 128

$ ../../whatismyschema/whatismyschema.py /tmp/z.csv 
+----+--------+--------+
|Name|Type    |Null    |
+----+--------+--------+
|col0|tinyint |NOT NULL|
+----+--------+--------+
|col1|tinyint |NOT NULL|
+----+--------+--------+
|col2|tinyint |NOT NULL|
+----+--------+--------+
|col3|smallint|NOT NULL|
+----+--------+--------+
|col4|smallint|NOT NULL|
+----+--------+--------+
|col5|smallint|NOT NULL|
+----+--------+--------+
|col6|smallint|NOT NULL|
+----+--------+--------+
|col7|smallint|NOT NULL|
+----+--------+--------+
|col8|smallint|NOT NULL|
+----+--------+--------+

**Comment by t1mm3** [comment]
Fixed with e8ef812c84d25d9f10725fbacbcccbb12144ecd3
